#!/bin/sh

case "$1" in
    remove|upgrade|deconfigure)
    	invoke-rc.d bwbar stop
    ;;
    failed-upgrade)
    ;;
    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

#DEBHELPER#

exit 0

